### PR TITLE
Remove np.real cast at inverse transform

### PR DESCRIPTION
**Pull request by faroit**

### CODE REVIEW

**Comment by faroit** [comment]
@nils-werner you can now pass your own transform to ispectrogram (defaults to ```np.real(transform)```).

**Comment by faroit** [comment]
if this is ready to merge, please bump up the version

**Comment by nils-werner** [comment]
Does it make sense to use

    if halved:
        numpy.real(scipy.fftpack.ifft(*args, **kwargs))
    else:
        scipy.fftpack.ifft

?

**Comment by nils-werner** [comment]
Please define two functions, depending on `halved`, instead of globally using that variable inside the function.

**Pull request closed without merging**
